name: release

on:
 workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.3

    - name: Update Rubygems
      run: gem update --system 3.1.0

    - name: Clone repository
      uses: actions/checkout@v2
      with:
        ref: ${{ env.GITHUB_REF }}

    - name: Release
      env:
        BLACKSMITH_FORGE_TOKEN: ${{ secrets.FORGE_API_KEY }}
      run: | 
        bundle install --with release
        bundle exec rake module:build
        bundle exec rake module:push
